[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.buildArgs]
NEXT_PUBLIC_API_URL = "$NEXT_PUBLIC_API_URL"

[deploy]
startCommand = "bun run start"
healthcheckPath = "/"
healthcheckTimeout = 100
